alias: put-go-pdfs
automation_alias: script
automation_uid: 5b4e0237da074764
cache: false
category: MLC Script Template
deps:
  - tags: get,rclone-config,_config-name.go-pdfs-out
    env:
      MLC_RCLONE_DRIVE_FOLDER_ID: 1auwx-H5_2A4tOHP9LdptX8H3JdCYXBgk
new_env_keys:
- MLC_GO_PDFS_OUT
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- drive
- pdfs
- put
- go
uid: 248468e1ae1e43eb
