alias: add-pdf-cover
automation_alias: script
automation_uid: 5b4e0237da074764
cache: false
tags:
- add
- cover
- pdf
deps:
  - tags: get,apt-package,_package.pdftk
    env:
      MLC_APT_CHECK_CMD: 'pdftk --version'
uid: 347b7ca88c30485a
new_env_keys:
  - MLC_PDF_OUTPUT_FILE_PATH
variations:
  go-cse: {}
  vol1: {}
  go-cse,vol1:
    env:
      MLC_PDF_COVER_PATH: <<<MLC_TMP_CURRENT_SCRIPT_PATH>>>/covers/vol1-cover.pdf
      MLC_PDF_FILE_PATH: '<<<MLC_GO_PDFS_OUT>>>/filter1_volume1.pdf'
      MLC_PDF_OUTPUT_FILE_PATH: '<<<MLC_GO_PDFS_OUT>>>/gatecse-volume1_w_cover.pdf'

  vol2: {}
  go-cse,vol2:
    env:
      MLC_PDF_COVER_PATH: <<<MLC_TMP_CURRENT_SCRIPT_PATH>>>/covers/vol2-cover.pdf
      MLC_PDF_FILE_PATH: '<<<MLC_GO_PDFS_OUT>>>/filter1_volume2.pdf'
      MLC_PDF_OUTPUT_FILE_PATH: '<<<NLC_PDFS_OUT>>>/gatecse-volume2_w_cover.pdf'
  isro: {}
  tifr: {}
  nielit: {}
  ugcnet: {}

  go-cse,isro:
    env:
      MLC_PDF_COVER_PATH: <<<MLC_TMP_CURRENT_SCRIPT_PATH>>>/covers/isro-cse-cover.pdf
      MLC_PDF_FILE_PATH: '<<<MLC_GO_PDFS_OUT>>>/isro.pdf'
      MLC_PDF_OUTPUT_FILE_PATH: '<<<MLC_GO_PDFS_OUT>>>/isro_w_cover.pdf'
  go-cse,tifr:
    env:
      MLC_PDF_COVER_PATH: <<<MLC_TMP_CURRENT_SCRIPT_PATH>>>/covers/tifr-cse-cover.pdf
      MLC_PDF_FILE_PATH: '<<<MLC_GO_PDFS_OUT>>>/tifr.pdf'
      MLC_PDF_OUTPUT_FILE_PATH: '<<<MLC_GO_PDFS_OUT>>>/tifr_w_cover.pdf'
  go-cse,nielit:
    env:
      MLC_PDF_COVER_PATH: <<<MLC_TMP_CURRENT_SCRIPT_PATH>>>/covers/nielit-cse-cover.pdf
      MLC_PDF_FILE_PATH: '<<<MLC_GO_PDFS_OUT>>>/nielit.pdf'
      MLC_PDF_OUTPUT_FILE_PATH: '<<<MLC_GO_PDFS_OUT>>>/nielit_w_cover.pdf'
  go-cse,ugcnet:
    env:
      MLC_PDF_COVER_PATH: <<<MLC_TMP_CURRENT_SCRIPT_PATH>>>/covers/ugcnet-cse-cover.pdf
      MLC_PDF_FILE_PATH: '<<<MLC_GO_PDFS_OUT>>>/ugcnet.pdf'
      MLC_PDF_OUTPUT_FILE_PATH: '<<<MLC_GO_PDFS_OUT>>>/ugcnet_w_cover.pdf'
