alias: make-go-pdf
automation_alias: script
automation_uid: 5b4e0237da074764
cache: false
tags:
- make
- go
- pdf
input_mapping:
  skip_pdf: MLC_SKIP_PDF_MAKE
  input: MLC_HTML_FILE_PATH
uid: 43bdc18426524e54
variations:
  go-em:
    deps:
      - tags: make,pdf,from-html,_go-em
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
  go-da:
    deps:
      - tags: make,pdf,from-html,_go-da
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes

  go-cse:
    env: {}
 
  isro: {}
  tifr: {}
  nielit: {}
  ugcnet: {}

  go-cse,isro:
    deps:
      - tags: make,pdf,from-html,_go-cse,_isro
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-cse,_isro

  go-cse,nielit:
    deps:
      - tags: make,pdf,from-html,_go-cse,_nielit
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-cse,_nielit

  go-cse,tifr:
    deps:
      - tags: make,pdf,from-html,_go-cse,_tifr
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-cse,_tifr

  go-cse,ugcnet:
    deps:
      - tags: make,pdf,from-html,_go-cse,_ugcnet
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-cse,_ugcnet

  go-cse,isro:
    deps:
      - tags: make,pdf,from-html,_go-cse,_isro
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-cse,_isro

  vol1: {} 
  go-cse,vol1:
    deps:
      - tags: make,pdf,from-html,_go-cse,_vol1
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-cse,_vol1 
      - tags: upload,pdf,release,_go-cse,_vol1 


  vol2: {} 
  go-cse,vol2:
    deps:
      - tags: make,pdf,from-html,_go-cse,_vol2
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-cse,_vol2
      - tags: upload,pdf,release,_go-cse,_vol2
