alias: make-go-pdf
automation_alias: script
automation_uid: 5b4e0237da074764
cache: false
tags:
- make
- go
- pdf
input_mapping:
  skip_pdf: MLC_SKIP_PDF_MAKE
  skip_cover: MLC_SKIP_PDF_COVER
  input: MLC_HTML_FILE_PATH
  upload: MLC_UPLOAD_PDF
  release: MLC_RELEASE_PDF
uid: 43bdc18426524e54

prehook_deps:
  - tags: put,go,pdfs
    enable_if_env:
      MLC_UPLOAD_PDF:
        - on
variations:
  with-answers:
    adr:
      pdf-from-html:
        tags:
          _with-answers
      add-cover:
        tags:
          _with-answers
  go-em:
    deps:
      - tags: make,pdf,from-html,_go-em
        names:
        - pdf-from-html
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
  go-da:
    deps:
      - tags: make,pdf,from-html,_go-da
        names:
        - pdf-from-html
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-da 
        skip_if_env:
          MLC_SKIP_PDF_COVER:
            - yes
      - tags: upload,pdf,release,_go-da
        enable_if_env:
          MLC_RELEASE_PDF:
            - on

  go-cse:
    env: {}
 
  isro: {}
  tifr: {}
  nielit: {}
  ugcnet: {}

  go-cse,isro:
    deps:
      - tags: make,pdf,from-html,_go-cse,_isro
        names:
        - pdf-from-html
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-cse,_isro
        skip_if_env:
          MLC_SKIP_PDF_COVER:
            - yes

  go-cse,nielit:
    deps:
      - tags: make,pdf,from-html,_go-cse,_nielit
        names:
        - pdf-from-html
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-cse,_nielit
        names:
        - add-cover
        skip_if_env:
          MLC_SKIP_PDF_COVER:
            - yes

  go-cse,tifr:
    deps:
      - tags: make,pdf,from-html,_go-cse,_tifr
        names:
        - pdf-from-html
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-cse,_tifr
        names:
        - add-cover
        skip_if_env:
          MLC_SKIP_PDF_COVER:
            - yes

  go-cse,ugcnet:
    deps:
      - tags: make,pdf,from-html,_go-cse,_ugcnet
        names:
        - pdf-from-html
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-cse,_ugcnet
        names:
        - add-cover
        skip_if_env:
          MLC_SKIP_PDF_COVER:
            - yes

  go-cse,isro:
    deps:
      - tags: make,pdf,from-html,_go-cse,_isro
        names:
        - pdf-from-html
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-cse,_isro
        names:
        - add-cover
        skip_if_env:
          MLC_SKIP_PDF_COVER:
            - yes

  vol1: {} 
  go-cse,vol1:
    deps:
      - tags: make,pdf,from-html,_go-cse,_vol1
        names:
        - pdf-from-html
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-cse,_vol1 
        names:
        - add-cover
        skip_if_env:
          MLC_SKIP_PDF_COVER:
            - yes
      - tags: upload,pdf,release,_go-cse,_vol1 
        enable_if_env:
          MLC_RELEASE_PDF:
            - on


  vol2: {} 
  vol3: {} 
  go-cse,vol2:
    deps:
      - tags: make,pdf,from-html,_go-cse,_vol2
        names:
        - pdf-from-html
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-cse,_vol2
        names:
        - add-cover
        skip_if_env:
          MLC_SKIP_PDF_COVER:
            - yes
      - tags: upload,pdf,release,_go-cse,_vol2
        enable_if_env:
          MLC_RELEASE_PDF:
            - on
  
  go-cse,vol3:
    deps:
      - tags: make,pdf,from-html,_go-cse,_vol3
        names:
        - pdf-from-html
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-cse,_vol3
        names:
        - add-cover
        skip_if_env:
          MLC_SKIP_PDF_COVER:
            - yes
      - tags: upload,pdf,release,_go-cse,_vol3
        enable_if_env:
          MLC_RELEASE_PDF:
            - on
  go-ece:
    deps:
      - tags: make,pdf,from-html,_go-ece
        names:
        - pdf-from-html
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-ece 
        names:
        - add-cover
        skip_if_env:
          MLC_SKIP_PDF_COVER:
            - yes
      - tags: upload,pdf,release,_go-ece
        enable_if_env:
          MLC_RELEASE_PDF:
            - on
  go-ee:
    deps:
      - tags: make,pdf,from-html,_go-ee
        names:
        - pdf-from-html
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-ee 
        names:
        - add-cover
        skip_if_env:
          MLC_SKIP_PDF_COVER:
            - yes
      - tags: upload,pdf,release,_go-ee
        enable_if_env:
          MLC_RELEASE_PDF:
            - on
  go-me:
    deps:
      - tags: make,pdf,from-html,_go-me
        names:
        - pdf-from-html
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-me 
        names:
        - add-cover
        skip_if_env:
          MLC_SKIP_PDF_COVER:
            - yes
      - tags: upload,pdf,release,_go-me
        enable_if_env:
          MLC_RELEASE_PDF:
            - on
  go-ce:
    deps:
      - tags: make,pdf,from-html,_go-ce
        names:
        - pdf-from-html
        skip_if_env:
          MLC_SKIP_PDF_MAKE:
            - yes
      - tags: add,pdf,cover,_go-ce 
        names:
        - add-cover
        skip_if_env:
          MLC_SKIP_PDF_COVER:
            - yes
      - tags: upload,pdf,release,_go-ce
        enable_if_env:
          MLC_RELEASE_PDF:
            - on
