alias: get-go-html
automation_alias: script
automation_uid: 5b4e0237da074764
category: MLC Script Template
deps:
  - tags: get,rclone-config,_config-name.go-pdfs-html
    env: 
      MLC_RCLONE_DRIVE_FOLDER_ID: 17YlxqPLRY8xKkwa1bMkSVTQpeFQV72Wr
cache: false
new_env_keys:
- MLC_GO_PDFS_HTML_ROOT
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- go
- html
- get
uid: 82a921e0a31a4395
