alias: get-go-html
automation_alias: script
automation_uid: 5b4e0237da074764
category: MLC Script Template
deps: []
cache: true
new_env_keys:
- MLC_GO_PDFS_HTML_ROOT
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- go
- html
- get
env:
  MLC_RCLONE_CONFIG_CMD: 'rclone config create go-pdfs drive config_is_local=false scope=drive.readonly root_folder_id=17YlxqPLRY8xKkwa1bMkSVTQpeFQV72Wr'
  MLC_RCLONE_CONNECT_CMD: 'rclone config reconnect go-pdfs:'
uid: 82a921e0a31a4395
