alias: make-pdf-from-html
automation_alias: script
automation_uid: 5b4e0237da074764
cache: false
tags:
- make
- from-html
- pdf
deps:
  - tags: get,wkhtmltopdf,_with-qt
  - tags: get,go,html
    skip_if_env:
      MLC_HTML_FILE_PATH:
      - on
uid: 403a21dfa7bc434a
input_mapping:
  input: MLC_HTML_FILE_PATH
variations:
  go-da:
    group: branch
    env:
      MLC_GO_PDF_BRANCH: da
      MLC_GO_PDF_TITLE: 'GATEOverflow for GATE DA'
      MLC_GO_HTML_FOLDER_NAME: gate_overflow_for_gate_cse
      MLC_GO_PDF_JS_DELAY: 3880000
      MLC_GO_PDF_SCALE: '1.0'
      MLC_GO_HTML_FILE_NAME: book_gate_da.html 
      MLC_GO_PDF_NAME: da.pdf
  go-em:
    group: branch
    env:
      MLC_GO_PDF_BRANCH: cse
      MLC_GO_PDF_TITLE: 'GATEOverflow for GATECSE'
      MLC_GO_HTML_FOLDER_NAME: gate_overflow_for_gate_cse
      MLC_GO_PDF_JS_DELAY: 388000
      MLC_GO_PDF_SCALE: '0.7'
      MLC_GO_HTML_FILE_NAME: book_gate_em.html 
      MLC_GO_PDF_NAME: em.pdf
  go-cse:
    group: branch
    default: true
    env:
      MLC_GO_PDF_BRANCH: cse
      MLC_GO_PDF_TITLE: 'GATEOverflow for GATECSE'
      MLC_GO_HTML_FOLDER_NAME: gate_overflow_for_gate_cse
  isro:
    group: exam
  tifr:
    group: exam
  nielit:
    group: exam
  ugcnet:
    group: exam

  go-cse,isro:
    default_env:
      MLC_GO_PDF_JS_DELAY: 788000
      MLC_GO_HTML_FILE_NAME: book_filter2.html 
      MLC_GO_PDF_SCALE: '0.7'
      MLC_GO_PDF_NAME: isro.pdf

  go-cse,tifr:
    default_env:
      MLC_GO_PDF_JS_DELAY: 588000
      MLC_GO_HTML_FILE_NAME: book_filter5.html 
      MLC_GO_PDF_SCALE: '0.7'
      MLC_GO_PDF_NAME: tifr.pdf

  go-cse,nielit:
    default_env:
      MLC_GO_PDF_JS_DELAY: 988000
      MLC_GO_HTML_FILE_NAME: book_filter4.html 
      MLC_GO_PDF_SCALE: '0.7'
      MLC_GO_PDF_NAME: nielit.pdf

  go-cse,ugcnet:
    default_env:
      MLC_GO_PDF_JS_DELAY: 4880000
      MLC_GO_HTML_FILE_NAME: book_filter6.html 
      MLC_GO_PDF_SCALE: '0.7'
      MLC_GO_PDF_NAME: ugcnet.pdf

  vol1:
    group: volume
    default: true
  vol2:
    group: volume

  go-cse,vol1:
    default_env:
      MLC_GO_PDF_JS_DELAY: 488000
      MLC_GO_HTML_FILE_NAME: book_filter1_volume1.html 
      MLC_GO_PDF_SCALE: '0.7'
      MLC_GO_PDF_NAME: filter1_volume1.pdf
  go-cse,vol2:
    default_env:
      MLC_GO_PDF_JS_DELAY: 4880000 
      MLC_GO_HTML_FILE_NAME: book_filter1_volume2.html 
      MLC_GO_PDF_SCALE: '1.0'
      MLC_GO_PDF_NAME: filter1_volume2.pdf


