name: Build GO PDF

on:
  schedule:
    - cron: "1 1 * * *"
  workflow_dispatch: {}

jobs:
  go-pdf-make:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]      
        
  
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Configure git longpaths (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        git config --system core.longpaths true

    - name: Install mlc-scripts
      run: |
        pip install mlc-scripts
        mlc pull repo gateoverflow@go-pdfs

    - name: Test Build (Linux/macOS)
      run: |
        mlcr download,file --url=https://github.com/GATEOverflow/GO-PDFs/releases/download/ugcnet/book_filter6.html
        mlcr make,go,pdf,_go-cse,_vol1  --input=book_filter6.html -v --quiet --skip_cover
      
